GuidePlatform/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path(r"app/Guide/",
         include(r"appGuide.urls", namespace = "appGuide")),

]

appGuide/urls.py
from django.urls import path

from appGuide.views.search1 import GuidableTimeListView, GuidableTimeIntervalView, search_guide
from appGuide.views.reserve1_2 import ReserveGuideTimeView

from appGuide.views.entry1 import EntryView

app_name = "appGuide"

urlpatterns = [

    path("search_guide",
         GuidableTimeIntervalView.as_view(), name ="search_guide"),
    path("reserve_guide/<int:pk>/<str:cand_time_interval>", # ex. 202002031000_202002031130
         ReserveGuideTimeView.as_view(), name="reserve_guide"),

    path("entry",
         EntryView.as_view(),
         name="entry"),

    ]

appGuide/forms.py
import datetime
from django.utils import timezone

from django import forms
from .models import *

class SearchGuideForm(forms.Form):

    req_time_from = \
        forms.DateTimeField(
            # widget   = forms.DateTimeInput(
            # attrs    = { "type"  : "datetime-local",
            #              "value" : timezone.datetime.now().strftime('%Y-%m-%dT%H:%M')}),
            # input_formats=['%Y-%m-%dT%H:%M'],
            required = True,
            label    = "希望日時開始")

    req_time_to = \
        forms.DateTimeField(
            # widget   = forms.DateTimeInput(
            # attrs    = { "type"  : "datetime-local",
            #              "value" : timezone.datetime.now().strftime('%Y-%m-%dT%H:%M')}),
            # input_formats = [ '%Y-%m-%dT%H:%M' ],
            required = True,
            label    = "希望日時終了")

    place_choices = forms.ModelMultipleChoiceField(
        queryset = Spot.objects.all(),
        widget   = forms.CheckboxSelectMultiple(),
        label    = "希望観光場所",
        required = False)

appGuide/forms/reserve_form.py
import datetime
from django.utils import timezone

from django import forms
from appGuide.models import *


class TouristReservationForm(forms.ModelForm):

    spot = forms.ModelChoiceField(
        queryset = Spot.objects.all(),
        label    = "希望観光地")

    class Meta:
        model = Tourist
        fields = (
            "user_sei",
            "user_mei",
            "user_seifuri",
            "user_meifuri",
            "user_gender",
            "user_seinen",
            "user_tel",
            "user_email",
            "user_pass",
            "user_post",
            "user_address1",
            "user_address2",
            "user_address3",
        )

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields[ 'user_pass' ].widget = forms.PasswordInput()

appGuide/forms/search_form.py
import datetime
from django.utils import timezone

from django import forms
from appGuide.models import *

class SearchGuideForm(forms.Form):

    req_time_from = \
        forms.DateTimeField(
            # widget   = forms.DateTimeInput(
            # attrs    = { "type"  : "datetime-local",
            #              "value" : timezone.datetime.now().strftime('%Y-%m-%dT%H:%M')}),
            # input_formats=['%Y-%m-%dT%H:%M'],
            required = True,
            label    = "希望日時開始")

    req_time_to = \
        forms.DateTimeField(
            # widget   = forms.DateTimeInput(
            # attrs    = { "type"  : "datetime-local",
            #              "value" : timezone.datetime.now().strftime('%Y-%m-%dT%H:%M')}),
            # input_formats = [ '%Y-%m-%dT%H:%M' ],
            required = True,
            label    = "希望日時終了")

    place_choices = forms.ModelMultipleChoiceField(
        queryset = Spot.objects.all(),
        widget   = forms.CheckboxSelectMultiple(),
        label    = "希望観光場所",
        required = False)

appGuide/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render

from .models import *
from .forms import SearchGuideForm

def search_guide(request):

    search_guide_form = SearchGuideForm()

    return render(request,
                  'appGuide/search_test1_1.html',
                  { "search_guide_form" : search_guide_form })



def testview1(request):

    return render(request,
                  'appGuide/testview1_1.html',
                  {})

def testview2(request):

    return render(request,
                  'appGuide/testview2_1.html',
                  {})

appGuide/views/entry1.py
# The following may be used for extracting portion of available time frames:
# pip install portion
# https://github.com/AlexandreDecan/portion

from datetime import datetime

from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView

from ..models import *
from ..forms.reserve_form import TouristReservationForm

from ..modules.datetime_with_timezone1 import datetime_str_localize
from ..modules.search_guidable_time_intervals1_1 import check_avail_full_interval

from pprint import pprint

class EntryView(TemplateView):

    template_name = "appGuide/entry1.html"

appGuide/views/reserve1_2.py
# The following may be used for extracting portion of available time frames:
# pip install portion
# https://github.com/AlexandreDecan/portion

from datetime import datetime

from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView

from ..models import *
from ..forms.reserve_form import TouristReservationForm

from ..modules.datetime_with_timezone1 import datetime_str_localize
from ..modules.search_guidable_time_intervals1_1 import check_avail_full_interval

from pprint import pprint

class ReserveGuideTimeView(TemplateView):

    template_name = "appGuide/reserve_guidetime1_2.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        guidable_time = GuidableTime.objects.get(pk = self.kwargs[ "pk" ])
        cdtimintvlstr = self.kwargs[ "cand_time_interval" ]

        req_time_from, req_time_to = [
            datetime_str_localize(tmpstr, "%Y%m%d%H%M")
            for tmpstr in cdtimintvlstr.split("_")
        ]

        if "reserve_form" not in vars(self):
            self.reserve_form = TouristReservationForm()
            self.reserve_form.fields[ "spot" ].queryset = guidable_time.guide.get_guidable_spots()

        context[ "guidable_time" ] = guidable_time
        context[ "req_time_from" ] = req_time_from
        context[ "req_time_to"   ] = req_time_to
        context[ "reserve_form" ]  = self.reserve_form

        if "no_longer_available" in vars(self):
            if self.no_longer_available:
                context[ "No_longer_avail" ] = True
            else:
                context[ "No_longer_avail" ] = False
        else:
            context[ "No_longer_avail" ] = None

        return context


    def post(self, request, *args, **kwargs):

        guidable_time = GuidableTime.objects.get(pk=self.kwargs[ "pk" ])
        cdtimintvlstr = self.kwargs[ "cand_time_interval" ]

        self.reserve_form = TouristReservationForm(data = self.request.POST)

        if self.reserve_form.is_valid():

            tourist       = self.reserve_form.save()
            spot          = self.reserve_form.cleaned_data[ "spot" ]

            req_time_from, req_time_to = [
                datetime_str_localize(tmpstr, "%Y%m%d%H%M")
                for tmpstr in cdtimintvlstr.split("_")
            ]

            # Check once more to confirm that the time interval is
            # still available, - not occupied by other tourist.

            if check_avail_full_interval(guidable_time,
                                         req_time_from, req_time_to):
                Reservation.objects.create(
                    tourist               = tourist,
                    reservation_ymdt      = timezone.localtime(),
                    reservation_time_from = req_time_from,
                    reservation_time_to   = req_time_to,
                    spot                  = spot,
                    guidable_time         = guidable_time,
                )
                return HttpResponseRedirect(reverse("appGuide:search_guide"))

            else:
                self.no_longer_available = True

        return self.get(request, *args, **kwargs)

appGuide/views/search1.py
# The following may be used for extracting portion of available time frames:
# pip install portion
# https://github.com/AlexandreDecan/portion


from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView, TemplateView
from django.db.models import Q

from django.utils.timezone import localtime

from appGuide.models import *
from appGuide.forms.search_form import SearchGuideForm

from ..modules.search_guidable_time_intervals1_1 import  extract_guidable_time_intervals

from pprint import pprint

class GuidableTimeIntervalView(TemplateView):
    model = GuidableTime
    template_name = "appGuide/guidetime_interval1_1.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if "search_form" in vars(self):
            search_form = self.search_form
        else:
            search_form = SearchGuideForm()
        context[ "search_form" ] = search_form

        if "cand_time_intvals" in vars(self):
            cand_time_intvals = self.cand_time_intvals
        else:
            cand_time_intvals = None
        context[ "cand_time_intvals" ] = cand_time_intvals

        return context

    def post(self, request, *args, **kwargs):

        self.search_form = SearchGuideForm(data = self.request.POST)

        """ Checking double-booking of a tourist not implemented yet. """

        if "search_form" in vars(self) and self.search_form.is_valid():
            guidable_times = search_guidable_times(self.search_form.cleaned_data)
            req_time_from  = self.search_form.cleaned_data[ "req_time_from" ]
            req_time_to    = self.search_form.cleaned_data[ "req_time_to"   ]
            # self.request.session[ "Request time" ] = {
            #     "from" : req_time_from.strftime("%Y/%m/%d %H:%M"),
            #     "to"   : req_time_to.strftime("%Y/%m/%d %H:%M"),
            # }
            # self.request.session.modified = True

            self.cand_time_intvals = []
            for guidable_time in guidable_times:

                intervals_info = [
                    { "interval"     : interval,
                      "interval_str" :
                         localtime(interval.lower).strftime("%Y%m%d%H%M") + "_"
                         + localtime(interval.upper).strftime("%Y%m%d%H%M")
                     } for interval in extract_guidable_time_intervals(guidable_time,
                                                                       req_time_from,
                                                                       req_time_to) ]

                self.cand_time_intvals.append(
                    { "guidable_time" : guidable_time,
                      "intervals"     : intervals_info })

            # pprint(self.cand_time_intvals)

        return self.get(request, *args, **kwargs)


class GuidableTimeListView(ListView):
    model = GuidableTime
    template_name = "appGuide/guidetime_list1_3.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if "search_form" in vars(self):
            search_form = self.search_form
        else:
            search_form = SearchGuideForm()
        context[ "search_form" ] = search_form

        # print(search_form.place_choices, type(search_form.place_choices), dir(search_form.place_choices))
        # print(vars(search_form))
        # print(vars(SearchGuideForm)) # .place_choices)

        return context

    def get_queryset(self):
        """ CHECK FOR ALREADY RESERVED TIMEFRAMES!!! """

        queryset = self.model.objects.none()

        if "search_form" in vars(self) and self.search_form.is_valid():
            queryset = search_guidable_times(self.search_form.cleaned_data)
            self.request.session[ "Request time" ] = {
                "from" : self.search_form.cleaned_data[ "req_time_from" ].strftime("%Y/%m/%d %H:%M"),
                "to"   : self.search_form.cleaned_data[ "req_time_to"   ].strftime("%Y/%m/%d %H:%M"),
            }
            self.request.session.modified = True
            pprint(self.request.session[ "Request time" ])

            # pprint(self.search_form.cleaned_data)
        # else:
            # print("Invalid!")
            # print("search_form" in vars(self))

        return queryset

    def post(self, request, *args, **kwargs):

        # pprint(self.request.POST)
        # pprint(self.request.POST.getlist("place_choices"))
        self.search_form = SearchGuideForm(data = self.request.POST)
        return self.get(request, *args, **kwargs)


def search_guidable_times(iform_input):

    # pprint(iform_input)
    # for guidable_time in GuidableTime.objects.all():
    #     print(guidable_time.guidable_time_from, guidable_time.guidable_time_to)

    queryset1 = GuidableTime.objects.filter(
        Q(guidable_time_from__gte = iform_input[ "req_time_from" ],
          guidable_time_from__lt  = iform_input[ "req_time_to"],
          guide__guidablespot__spot__in = iform_input[ "place_choices" ],) |
        Q(guidable_time_to__gte   = iform_input[ "req_time_from" ],
          guidable_time_to__lt    = iform_input[ "req_time_to" ],
          guide__guidablespot__spot__in = iform_input[ "place_choices" ],) |
        Q(guidable_time_from__lt = iform_input["req_time_from"],
          guidable_time_to__gte  = iform_input["req_time_to"],
          guide__guidablespot__spot__in=iform_input["place_choices"], )).distinct()

    return queryset1


class GuideListView(ListView):
    model = Guide
    template_name = "appGuide/guide_list1.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if "search_form" in vars(self):
            search_form = self.search_form
        else:
            search_form = SearchGuideForm()
        context[ "search_form" ] = search_form

        return context

    def get_queryset(self):

        queryset = self.model.objects.none()

        if "search_form" in vars(self) and self.search_form.is_valid():
            queryset = self.model.objects.all()

        return queryset

    def post(self, request, *args, **kwargs):

        self.search_form = SearchGuideForm(data = self.request.POST)
        return self.get(request, *args, **kwargs)



def search_guide(request):

    search_guide_form = SearchGuideForm()

    return render(request,
                  'appGuide/search_test1_2.html',
                  { "search_guide_form" : search_guide_form })

appGuide/templates/appGuide/Guide_base1_1.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>

    <meta charset="utf-8">
    <title>Takenori's Tsuruoka Guide Platform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="{% static 'Common/jquery-3.4.1/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'Common/bootstrap-4.4.1-dist/css/bootstrap.css' %}">
    <script type="text/javascript" src="{% static 'Common/bootstrap-4.4.1-dist/js/bootstrap.js' %}"></script>

    {% block header_script %}
        <script>

        </script>
    {% endblock %}

</head>

<body>


{% block main_body %}
...
{% endblock %}

</body>

</html>

appGuide/templates/appGuide/Guide_base1_2.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>

    <meta charset="utf-8">
    <title>Takenori's Tsuruoka Guide Platform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'Common/bootstrap-4.4.1-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Common/datetimepicker20200314/jquery.datetimepicker.css' %}">
    <script type="text/javascript" src="{% static 'Common/jquery-3.4.1/jquery-3.4.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'Common/bootstrap-4.4.1-dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'Common/datetimepicker20200314/build/jquery.datetimepicker.full.min.js' %}"></script>

    {% block header_script %}
        <script>

        </script>
    {% endblock %}

</head>

<body>
<div class="container">

    <div class="page-header mt-3 p-2 bg-info">
        <h1>鶴岡観光語り部プラットフォーム</h1>
        <p>プロトタイプ版 Ver 0.1 (2020/03/16)</p>
    </div>

    {% block main_body %}
    ...
    {% endblock %}

</div>
</body>

</html>

appGuide/templates/appGuide/entry1.html
{% extends 'appGuide/Guide_base1_2.html' %}
{% load static %}

{% block main_body %}


    {# ここから #}


<H2>ようこそ！！</H2>
    <H3>ゆっくりしていって</H3>
    <H4>下さいね</H4>

<p class="text-muted">慶應義塾大学</p>
<p class="text-primary">先端生命科学研究所</p>
<p class="text-success">Institute for Advanced Biosciences</p>
<p class="text-info">Keio University</p>
<p class="text-warning">鶴岡</p>
<p class="text-danger">Tsuruoka</p>

<p class="bg-primary">先端生命科学研究所</p>
<p class="bg-success">Institute for Advanced Biosciences</p>
<p class="bg-info">Keio University</p>
<p class="bg-warning">鶴岡</p>
<p class="bg-danger">Tsuruoka</p>

    <span class="badge badge-info">IAB</span>

<div class="card">
    <div class="card-header">
      ご案内
    </div>
    <div class="card-body">
貴方が気に入るガイドがきっと見つかります。
    </div>
</div>

    {# ここまでの間に色々と書いてみる #}


{% endblock %}

appGuide/templates/appGuide/guide_list1.html
{% extends 'appGuide/Guide_base1_2.html' %}
{% load static %}

{% block main_body %}

<H2>ガイド検索</H2>

<form method="post">
{% csrf_token %}

    {{ search_form }}

        <button type="submit" id="id_submit_button">ガイドを探す</button>
         (テスト中につき、機能しません)

</form>

    {% if object_list %}
        <h3>条件に合うガイド</h3>
        <ul>
        {% for guide in object_list %}
            <li>{{ guide }}</li>
        {% endfor %}
        </ul>


    {% endif %}

{% endblock %}

appGuide/templates/appGuide/guidetime_interval1_1.html
{% extends 'appGuide/Guide_base1_2.html' %}
{% load static %}

{% block header_script %}

    <script>
        $(function(){
            $.datetimepicker.setLocale('ja');
            $('#{{ search_form.req_time_from.auto_id }}').datetimepicker({ format : 'Y-m-d H:i',
                                                                           step   : 30 });
            $('#{{ search_form.req_time_to.auto_id }}').datetimepicker({ format : 'Y-m-d H:i',
                                                                         step   : 30 });
        });

        function turnonalltspots(){

            var spots = document.querySelectorAll('input[id^="id_place_choices_"]');
            console.log(spots);
            for(var i = 0;i < spots.length; i++){
                console.log(spots[i]);
                spots[i].checked = true;
            }
        }

    </script>

{% endblock %}

{% block main_body %}

<H2 class="mt-2 p-2">ガイド検索</H2>

<form method="post">
{% csrf_token %}

    <p>
        {{ search_form.req_time_from.errors }}
        <label for="{{ search_form.req_time_from.id_for_label }}">{{ search_form.req_time_from.label }}</label>
        {{ search_form.req_time_from }}

        {{ search_form.req_time_to.errors }}
        <label for="{{ search_form.req_time_to.id_for_label }}">{{ search_form.req_time_to.label }}</label>
        {{ search_form.req_time_to }}
    </p>

    <div class="container">
    {{ search_form.place_choices.errors }}
        <div class="row">
        {% for choice_spot in search_form.place_choices.field.choices.queryset %}

            <div class="col-md-4">
                <label for="id_place_choices_{{ forloop.counter0 }}">
                    {# {{ choice_spot.pk|stringformat:"d" }} {{ search_form.place_choices.value }} #}
                    {% if choice_spot.pk|stringformat:"d" in search_form.place_choices.value  %}
                        <input type="checkbox" name="place_choices" value="{{ choice_spot.pk }}" id="id_place_choices_{{ forloop.counter0 }}" checked>
                    {% else %}
                        <input type="checkbox" name="place_choices" value="{{ choice_spot.pk }}" id="id_place_choices_{{ forloop.counter0 }}">
                    {% endif %}
                    {{ choice_spot }} {# {{ choice_spot.pk }} #} {#  Check choice_spot.pk #}
                </label>
            </div>

        {% endfor %}
        </div>
    </div>

    <button type="button" class="btn btn-secondary" onclick="turnonalltspots()">全ての観光地を対象とする</button>

    <button type="submit" class="btn btn-primary" id="id_submit_button">ガイドを探す</button>


</form>

    {% if request.method == "POST" %}

        <h3 class="mt-3">条件に合うガイド</h3>

        {% if cand_time_intvals %}

            {% for guideavail in cand_time_intvals %}
                {% for interval_info in guideavail.intervals %}
                    <dl class="mb-2 bg-success">
                        <dt>{{ guideavail.guidable_time.guide }}</dt>
                        <dd>{{ guideavail.guidable_time.guide.get_guidable_spots_str }}</dd>
                        <dd>{{ interval_info.interval.lower }} - {{ interval_info.interval.upper }}</dd>
                    </dl>
                    <div class="mb-3">
                        <a href="{% url 'appGuide:reserve_guide' guideavail.guidable_time.pk interval_info.interval_str %}">このガイド・時間帯の予約へ</a>
                    </div>

                {% endfor %}
            {% endfor %}

             <p>※注意: 旅行者自身にダブルブッキングが起こらないよう、ご注意下さい。</p>

        {% else %}

            条件に合うガイドが見つかりませんでした。

        {%  endif %}


    {% endif %}

{% endblock %}

appGuide/templates/appGuide/reserve_guidetime1_2.html
{% extends 'appGuide/Guide_base1_2.html' %}
{% load static %}

{% block header_script %}

    <script>
        $(function(){
            $.datetimepicker.setLocale('ja');
            $('#{{ reserve_form.user_seinen.auto_id }}').datetimepicker({ format : 'Y-m-d',
                                                                          timepicker : false });
        });

    </script>

{% endblock %}


{% block main_body %}

<H2 class="mt-2 p-2">ガイド予約</H2>
    <dl class="mt-2 p-2">
        <dt>ガイド名</dt>
        <dd>{{ guidable_time.guide }}</dd>
        <dt>ガイド可能場所</dt>
        <dd>{{ guidable_time.guide.get_guidable_spots_str }}</dd>
        <dt>ガイド予約時間</dt>
        <dd>{{ req_time_from }} - {{ req_time_to }}</dd>
    </dl>

    {% if No_longer_avail %}
        <p class="text-warning">この時間帯は既に埋まってしまいました。</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        {# {{ reserve_form }} #}


        <div class="form-group">
            {{ reserve_form.spot.errors }}
            <label for="{{ reserve_form.spot.id_for_label }}">{{ reserve_form.spot.label }}</label>
            {{ reserve_form.spot }}
            {# class="form-control" not specified #}
        </div>

        <div class="form-row">
            <div class="col">
                {{ reserve_form.user_sei.errors }}
                <label for="{{ reserve_form.user_sei.id_for_label }}">{{ reserve_form.user_sei.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_sei.name }}" required id="{{ reserve_form.user_sei.auto_id }}">
            </div>
            <div class="col">
                {{ reserve_form.user_mei.errors }}
                <label for="{{ reserve_form.user_mei.id_for_label }}">{{ reserve_form.user_mei.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_mei.name }}" required id="{{ reserve_form.user_mei.auto_id }}">
            </div>
        </div>

        <div class="form-row">
            <div class="col">
                {{ reserve_form.user_seifuri.errors }}
                <label for="{{ reserve_form.user_seifuri.id_for_label }}">{{ reserve_form.user_seifuri.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_seifuri.name }}" required id="{{ reserve_form.user_seifuri.auto_id }}">
            </div>
            <div class="col">
                {{ reserve_form.user_meifuri.errors }}
                <label for="{{ reserve_form.user_meifuri.id_for_label }}">{{ reserve_form.user_meifuri.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_meifuri.name }}" required id="{{ reserve_form.user_meifuri.auto_id }}">
            </div>
        </div>

        <div class="form-group mt-3">
            {{ reserve_form.user_gender.errors }}
            <label for="{{ reserve_form.user_gender.id_for_label }}">{{ reserve_form.user_gender.label }}</label>
            {{ reserve_form.user_gender }}
            {# class="form-control" not specified #}
        </div>
        <div class="form-group mt-3">
            {{ reserve_form.user_seinen.errors }}
            <label for="{{ reserve_form.user_seinen.id_for_label }}">{{ reserve_form.user_seinen.label }}</label>
            {{ reserve_form.user_seinen }}
            (入力例: 1955-05-05)
            {# class="form-control" not specified #}
        </div>

        <div class="form-row">
            <div class="col">
                {{ reserve_form.user_tel.errors }}
                <label for="{{ reserve_form.user_tel.id_for_label }}">{{ reserve_form.user_tel.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_tel.name }}" required id="{{ reserve_form.user_tel.auto_id }}">
            </div>

            <div class="col">
                {{ reserve_form.user_email.errors }}
                <label for="{{ reserve_form.user_email.id_for_label }}">{{ reserve_form.user_email.label }}</label>
                <input type="email" class="form-control" name="{{ reserve_form.user_email.name }}" required id="{{ reserve_form.user_email.auto_id }}">
            </div>
        </div>

        <div class="form-group mt-3">
            {{ reserve_form.user_pass.errors }}
            <label for="{{ reserve_form.user_pass.id_for_label }}">{{ reserve_form.user_pass.label }}</label>
            {{ reserve_form.user_pass }}
            {# class="form-control" not specified #}
        </div>

        <div class="form-row">
            <div class="col">
                {{ reserve_form.user_post.errors }}
                <label for="{{ reserve_form.user_post.id_for_label }}">{{ reserve_form.user_post.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_post.name }}" required id="{{ reserve_form.user_post.auto_id }}">
            </div>

            <div class="col">
                {{ reserve_form.user_address1.errors }}
                <label for="{{ reserve_form.user_address1.id_for_label }}">{{ reserve_form.user_address1.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_address1.name }}" required id="{{ reserve_form.user_address1.auto_id }}">
            </div>
        </div>

        <div class="form-row">
            <div class="col">
                {{ reserve_form.user_address2.errors }}
                <label for="{{ reserve_form.user_address2.id_for_label }}">{{ reserve_form.user_address2.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_address2.name }}" required id="{{ reserve_form.user_address2.auto_id }}">
            </div>

            <div class="col">
                {{ reserve_form.user_address3.errors }}
                <label for="{{ reserve_form.user_address3.id_for_label }}">{{ reserve_form.user_address3.label }}</label>
                <input type="text" class="form-control" name="{{ reserve_form.user_address3.name }}" id="{{ reserve_form.user_address3.auto_id }}">
            </div>
        </div>


        <button type="submit" class="btn btn-primary" id="id_submit_button">予約する</button>

    </form>

    <p>※注意: 旅行者自身にダブルブッキングが起こらないよう、ご注意下さい。</p>

{% endblock %}